# Generated by Django 5.0.6 on 2024-07-01 09:07

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100, validators=[web.models.start_with])),
                ('eemail', models.EmailField(max_length=254, validators=[web.models.validate_mail])),
                ('econtact', models.CharField(max_length=15, validators=[web.models.mobile_no])),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
